package testlang

//go:generate go-enum --marshal -nocase

// Outcome is an enumeration of outcomes during a test.
/*
ENUM(
unset, // No outcome recorded yet.
inc,   // Inconclusive outcome.
fail,  // Failing outcome.
pass   // Passing outcome.
)
*/
// These are the same statuses understood in the CSP testing theory.
type Outcome uint8

// Most of the status constants are autogenerated by go-enum; see status_enum.go

const (
	FirstOutcome = OutcomeInc  // FirstOutcome is the first nonzero outcome.
	LastStatus   = OutcomePass // LastStatus is the last nonzero outcome.

	NumStatus = uint8(LastStatus) + 1 // NumStatus is the number of valid status entries.
)
