linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - style
    - test
    - unused
  disable:
    - rowserrcheck
    - wastedassign
    - ireturn
    - godox
    - musttag # this is throwing weird errors at the moment